# Generated by Django 5.2.8 on 2026-01-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_comment_commentlike_postlike_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at']},
        ),
    ]
