# Generated by Django 5.2.8 on 2026-01-13 13:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=50)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_post', to='social_media.post')),
            ],
        ),
    ]
